version: '3'

services:
    db:
        image: mysql:8.0.20
        container_name: db
        volumes:
            - "db_customers:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./kymatio/:/var/www/kymatio/
        networks:
            - symfony
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./kymatio/:/var/www/kymatio/
        ports:
            - 80:80
        networks:
            - symfony

volumes:
    db_customers:

networks:
    symfony: