nelmio_api_doc:
    documentation:
        info:
            title: Kymatio App
            description: This is an awesome app!
            version: 1.0.0
    areas: # to filter documented areas
        default:
            name_patterns: [ ^api ]
        internal:
            with_annotation: true